// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if credentials are valid before initializing
const isConfigValid = 
  SUPABASE_URL && 
  SUPABASE_URL.startsWith('http') && 
  SUPABASE_URL !== 'YOUR_SUPABASE_URL' &&
  SUPABASE_PUBLISHABLE_KEY &&
  SUPABASE_PUBLISHABLE_KEY !== 'YOUR_SUPABASE_ANON_KEY';

if (!isConfigValid && typeof window !== 'undefined') {
  console.warn(
    "Supabase configuration is missing or invalid. " +
    "Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment settings. " +
    "Current URL: " + SUPABASE_URL
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isConfigValid
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : new Proxy({} as any, {
      get(_, prop) {
        if (prop === 'auth') {
          return {
            onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
            getSession: () => Promise.resolve({ data: { session: null } }),
            signInWithOAuth: () => Promise.resolve({ error: new Error("Supabase is not configured") }),
            signInWithPassword: () => Promise.resolve({ error: new Error("Supabase is not configured") }),
            signUp: () => Promise.resolve({ error: new Error("Supabase is not configured") }),
            signOut: () => Promise.resolve(),
          };
        }
        if (prop === 'from') {
          return () => ({
            select: () => ({
              eq: () => ({
                limit: () => ({
                  maybeSingle: () => Promise.resolve({ data: null, error: null })
                })
              })
            }),
            insert: () => Promise.resolve({ error: new Error("Supabase is not configured") }),
            update: () => ({ eq: () => Promise.resolve({ error: new Error("Supabase is not configured") }) }),
          });
        }
        if (prop === 'functions') {
          return {
            invoke: () => Promise.resolve({ data: null, error: new Error("Supabase is not configured") }),
          };
        }
        return () => ({ data: null, error: new Error("Supabase is not configured") });
      }
    });
